# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66f4b4444082da4937fc1136c1b8f3a3db3c81770cd12e139f2a071a0789c1d3ef44cf595e1f9d7de0682016d53a93cb82942e88a63e5f923cde4e0abe63c89e

test:
  secret_key_base: bcd935ca676fb98be7ee1608024c48977cf2915a2bc906ab91a35ec93e81cbeee6c2c719cf0891d59befc5aab7492ac0e999fbee4093e9e792733e5ce2ddf73a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
